### ISSUE TITLE
Some errors here and there

### ISSUE THREAD

**Issue by Reptorian1125** [0xC0000054/gmic-sharp-pdn#2]
![image](https://user-images.githubusercontent.com/20409297/138573606-22050ca6-61bf-464b-a36c-23052be7c0f4.png)

Here's the list of errors I have. I do have gmic-sharp successfully built.

**Comment by 0xC0000054** [comment]
Sorry about that.

I redesigned the gmic-sharp API and had not checked in the gmic-sharp-pdn changes.
